[package]
name = "liquers-wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
liquers-core={path="../liquers-core"}
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.3"